# Generated by Django 3.0.8 on 2020-07-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(default='This is the test_bio', max_length=200),
            preserve_default=False,
        ),
    ]
